# Generated by Django 3.1.2 on 2020-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Furniture'), ('c', 'Electronics'), ('d', 'Miscellaneous'), ('e', 'Kitchen')], default=None, max_length=1),
        ),
    ]
