# Generated by Django 3.1.2 on 2020-10-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201012_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Furniture'), ('c', 'Electronics'), ('d', 'Miscellaneous'), ('e', 'Kitchen'), ('f', 'None')], default='None', max_length=1),
        ),
    ]
